package enums;

public enum Operation {
    PRIJAVI_SPORTSKI_OBJEKAT,
    UBACI_REZERVACIJU,
    PRETRAZI_REZERVACIJU,
    PROMENI_REZERVACIJU,
    VRATI_LISTU_STAVKI_REZERVACIJE,
    VRATI_LISTU_SVI_SPORTSKI_OBJEKAT,
    VRATI_LISTU_SVI_KORISNIK,
    VRATI_LISTU_SVI_TRENING,
    UBACI_KORISNIK,
    PRETRAZI_KORISNIK,
    PROMENI_KORISNIK,
    OBRISI_KORISNIK,
    VRATI_LISTU_SVI_KATEGORIJA_CLANSTVA,
    UBACI_TIP_OPREME,
    VRATI_LISTU_REZERVACIJA,
    VRATI_LISTU_KORISNIK
}
